version: '3.9'

services:
  api_gateway:
    build:
      context: ./api_gateway
    depends_on:
      - user_service
      - balance_service
      - rabbitmq
    ports:
      - "1432:8000"  
    networks:
      - app-network
    env_file:
      - ./api_gateway/.env 
    volumes:
      - ./api_gateway/app:/backend/app

  rabbitmq:
    image: rabbitmq:4.1.0
    ports:
      - "5672:5672"      
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - app-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  user_service:
    build:
      context: ./user_service
    depends_on:
      - user_db
      - rabbitmq
    ports:
      - "8001:8000"  
    networks:
      - app-network
    env_file:
      - ./user_service/.env  
    restart: always
    volumes:
      - ./user_service/app:/backend/app

  balance_service:
    build:
      context: ./balance_service
    depends_on:
      - balance_db
      - rabbitmq
    ports:
      - "8002:8000"  
    networks:
      - app-network
    env_file:
      - ./balance_service/.env  
    restart: always
    volumes:
      - ./balance_service/app:/backend/app
  order_service:
    build:
      context: ./order_service
    depends_on:
      - order_db
      - rabbitmq
    ports:
      - "8003:8000"  
    networks:
      - app-network
    env_file:
      - ./order_service/.env  
    restart: always
    volumes:
      - ./order_service/app:/backend/app
    

  user_db:
    image: postgres:17
    volumes:
      - user_pg_data:/var/lib/postgresql/data
    networks:
      - app-network
    depends_on:
      - rabbitmq
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_USERS}
    ports:
    - "5433:5432"
  
  balance_db:
    image: postgres:17
    volumes:
      - balance_pg_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always
    depends_on:
      - rabbitmq
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_BALANCES}
    ports:
    - "5434:5432"
  order_db:
    image: postgres:17
    volumes:
      - order_pg_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always
    depends_on:
      - rabbitmq
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_ORDERS}
    ports:
    - "5435:5432"
volumes:
  user_pg_data:
  balance_pg_data:
  order_pg_data:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge