version: '3.9'

services:
  api_gateway:
    build:
      context: ./api_gateway
    depends_on:
      - user_service
    ports:
      - "1432:8000"  
    networks:
      - app-network
    env_file:
      - ./api_gateway/.env 
  user_service:
    build:
      context: ./user_service
    depends_on:
      - user_db
    ports:
      - "8001:8000"  
    networks:
      - app-network
    env_file:
      - ./user_service/.env  
    restart: always

  user_db:
    image: postgres:17
    volumes:
      - user_pg_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_USERS}

volumes:
  user_pg_data:

networks:
  app-network:
    driver: bridge
