FROM python:3.12-slim

RUN apt-get update -qy && curl -sSL https://install.python-poetry.org | python3 -

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV POETRY_VERSION=1.8.3 \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_CACHE_DIR='/var/cache/pypoetry' \
    POETRY_HOME='/usr/local'


WORKDIR /backend

COPY pyproject.toml poetry.lock ./

RUN poetry install --no-root 

COPY ./src ./src
COPY ./alembic ./
COPY alembic.ini ./

CMD ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

EXPOSE 8000
